### ISSUE TITLE
pre-compiled .jar-Files

### ISSUE THREAD

**Issue by thimma11** [northem/northem-dark-intellij-idea-syntax#1]
It would be a big help if you could add the pre-compiled .jar-files for the northem-syntax themes too because I didn't manage to build them correctly :)
I love your themes, keep up the good work!

**Comment by arcticicestudio** [comment]
Sorry for my late reply, I've been busy with my job.

I added pre-compiled JAR files to the [0.1.0](https://github.com/arcticicestudio/northem-dark-intellij-idea-syntax/releases/tag/v0.1.0) release.

**Comment by thimma11** [comment]
No problem, take your time.
I appreciate your work very much :)
